# Available handlers: dockerhub, bitbucket
# Available runners: bash
handlers:
  /dockerhub:
    type: dockerhub
    auth: true
    log: true
    runners:
      bash:
        command: echo
        args: $PUSHER$ pushed new image to $REPO$:$TAG$
  /bitbucket:
    type: bitbucket
    auth: false
    log: true
    runners:
      bash:
        command: echo
        args: $PUSHER$ pushed new code to $REPO$/$BRANCH$

tls:
  key: server.key
  cert: server.crt

apikeys:
  - some-api-key
