# Available handlers: dockerhub
# Available runners: bash
handlers:
  /dockerhub:
    type: dockerhub
    auth: true
    runners:
      bash:
        command: ls
        args: -la

tls:
  key: server.key
  cert: server.crt

apikeys:
  - some-api-key
