# Available handlers: dockerhub
# Available runners: bash
handlers:
  /dockerhub:
    type: dockerhub
    auth: true
    log: true
    runners:
      bash:
        command: echo
        args: $PUSHER$ pushed new image to $REPO$:$TAG$

tls:
  key: server.key
  cert: server.crt

apikeys:
  - some-api-key
